before_script:
- composer install
- cp schema/propel.php.dev.dist schema/propel.php;
- composer dump-autoload

test:app:
  script:
  - ./vendor/bin/phpunit test --coverage-html coverage --coverage-clover coverage/clover.xml --configuration phpunit.xml -v
  
  after_script:
  - ./vendor/bin/php-coverage-badger coverage/clover.xml coverage/coverage.svg

  artifacts:
    paths:
    - coverage
